// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ItineraryDocumentDataSlicesSlice =
  | TripMapSlice
  | BookingFeaturesSlice
  | TopTourSummarySlice;

/**
 * Content for itinerary documents
 */
interface ItineraryDocumentData {
  /**
   * Slice Zone field in *itinerary*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ItineraryDocumentDataSlicesSlice> /**
   * Meta Title field in *itinerary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: itinerary.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *itinerary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: itinerary.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *itinerary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * itinerary document from Prismic
 *
 * - **API ID**: `itinerary`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ItineraryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ItineraryDocumentData>,
    "itinerary",
    Lang
  >;

export type AllDocumentTypes = ItineraryDocument;

/**
 * Primary content in *BookingFeatures → Default → Primary*
 */
export interface BookingFeaturesSliceDefaultPrimary {
  /**
   * feature 1 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_1: prismic.RichTextField;

  /**
   * feature 2 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_2: prismic.RichTextField;

  /**
   * feature 3 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_3: prismic.RichTextField;

  /**
   * additional information field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.additional_information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  additional_information: prismic.RichTextField;
}

/**
 * Default variation for BookingFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingFeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BookingFeatures*
 */
type BookingFeaturesSliceVariation = BookingFeaturesSliceDefault;

/**
 * BookingFeatures Shared Slice
 *
 * - **API ID**: `booking_features`
 * - **Description**: BookingFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingFeaturesSlice = prismic.SharedSlice<
  "booking_features",
  BookingFeaturesSliceVariation
>;

/**
 * Item in *TopTourSummary → Default → Primary → year*
 */
export interface TopTourSummarySliceDefaultPrimaryYearItem {
  /**
   * year field in *TopTourSummary → Default → Primary → year*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.year[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Primary content in *TopTourSummary → Default → Primary*
 */
export interface TopTourSummarySliceDefaultPrimary {
  /**
   * Top Tour Image field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.top_tour_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  top_tour_image: prismic.ImageField<never>;

  /**
   * trip year field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  trip_year: prismic.RichTextField;

  /**
   * year field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.year[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  year: prismic.GroupField<Simplify<TopTourSummarySliceDefaultPrimaryYearItem>>;

  /**
   * title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * travel field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.travel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  travel: prismic.RichTextField;

  /**
   * travel content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.travel_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  travel_content: prismic.RichTextField;

  /**
   * accomodation field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.accomodation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accomodation: prismic.RichTextField;

  /**
   * accomodation content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.accomodation_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accomodation_content: prismic.RichTextField;

  /**
   * meals field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.meals
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meals: prismic.RichTextField;

  /**
   * meals content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.meals_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meals_content: prismic.RichTextField;

  /**
   * itinerary field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.itinerary
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itinerary: prismic.RichTextField;

  /**
   * itinerary content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.itinerary_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itinerary_content: prismic.RichTextField;

  /**
   * cta title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_title: prismic.RichTextField;

  /**
   * cta content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.cta_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_content: prismic.RichTextField;

  /**
   * trip code field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  trip_code: prismic.RichTextField;
}

/**
 * Default variation for TopTourSummary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopTourSummarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TopTourSummary*
 */
type TopTourSummarySliceVariation = TopTourSummarySliceDefault;

/**
 * TopTourSummary Shared Slice
 *
 * - **API ID**: `top_tour_summary`
 * - **Description**: TopTourSummary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySlice = prismic.SharedSlice<
  "top_tour_summary",
  TopTourSummarySliceVariation
>;

/**
 * Item in *TripMap → Default → Primary → legend*
 */
export interface TripMapSliceDefaultPrimaryLegendItem {
  /**
   * icon field in *TripMap → Default → Primary → legend*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * label field in *TripMap → Default → Primary → legend*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *TripMap → Default → Primary*
 */
export interface TripMapSliceDefaultPrimary {
  /**
   * title field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * map field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.map
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  map: prismic.ImageField<never>;

  /**
   * legend field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legend: prismic.GroupField<Simplify<TripMapSliceDefaultPrimaryLegendItem>>;
}

/**
 * Default variation for TripMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripMapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TripMap*
 */
type TripMapSliceVariation = TripMapSliceDefault;

/**
 * TripMap Shared Slice
 *
 * - **API ID**: `trip_map`
 * - **Description**: TripMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripMapSlice = prismic.SharedSlice<
  "trip_map",
  TripMapSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ItineraryDocument,
      ItineraryDocumentData,
      ItineraryDocumentDataSlicesSlice,
      AllDocumentTypes,
      BookingFeaturesSlice,
      BookingFeaturesSliceDefaultPrimary,
      BookingFeaturesSliceVariation,
      BookingFeaturesSliceDefault,
      TopTourSummarySlice,
      TopTourSummarySliceDefaultPrimaryYearItem,
      TopTourSummarySliceDefaultPrimary,
      TopTourSummarySliceVariation,
      TopTourSummarySliceDefault,
      TripMapSlice,
      TripMapSliceDefaultPrimaryLegendItem,
      TripMapSliceDefaultPrimary,
      TripMapSliceVariation,
      TripMapSliceDefault,
    };
  }
}
