// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DayByDayAccordionDocumentDataSlicesSlice = DayByDayAccordionContentSlice;

/**
 * Content for day by day accordion documents
 */
interface DayByDayAccordionDocumentData {
  /**
   * Slice Zone field in *day by day accordion*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DayByDayAccordionDocumentDataSlicesSlice>;
}

/**
 * day by day accordion document from Prismic
 *
 * - **API ID**: `day_by_day_accordion`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DayByDayAccordionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DayByDayAccordionDocumentData>,
    "day_by_day_accordion",
    Lang
  >;

type ItineraryDocumentDataSlicesSlice =
  | FaqSlice
  | AboutTripSlice
  | DayByDayAccordionContentSlice
  | DayByDayItinerarySlice
  | TripMapSlice
  | BookingFeaturesSlice
  | TopTourSummarySlice;

/**
 * Content for itinerary documents
 */
interface ItineraryDocumentData {
  /**
   * Slice Zone field in *itinerary*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ItineraryDocumentDataSlicesSlice> /**
   * Meta Title field in *itinerary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: itinerary.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *itinerary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: itinerary.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *itinerary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itinerary.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * itinerary document from Prismic
 *
 * - **API ID**: `itinerary`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ItineraryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ItineraryDocumentData>,
    "itinerary",
    Lang
  >;

export type AllDocumentTypes = DayByDayAccordionDocument | ItineraryDocument;

/**
 * Item in *AboutTrip → Default → Primary → details*
 */
export interface AboutTripSliceDefaultPrimaryDetailsItem {
  /**
   * detail field in *AboutTrip → Default → Primary → details*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.details[].detail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  detail: prismic.RichTextField;
}

/**
 * Primary content in *AboutTrip → Default → Primary*
 */
export interface AboutTripSliceDefaultPrimary {
  /**
   * title field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * additional information field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.additional_information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  additional_information: prismic.KeyTextField;

  /**
   * icon field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * details field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.details[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  details: prismic.GroupField<
    Simplify<AboutTripSliceDefaultPrimaryDetailsItem>
  >;

  /**
   * type field in *AboutTrip → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: about_trip.default.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"sightseeing" | "travel">;
}

/**
 * Default variation for AboutTrip Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTripSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTripSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutTrip*
 */
type AboutTripSliceVariation = AboutTripSliceDefault;

/**
 * AboutTrip Shared Slice
 *
 * - **API ID**: `about_trip`
 * - **Description**: AboutTrip
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTripSlice = prismic.SharedSlice<
  "about_trip",
  AboutTripSliceVariation
>;

/**
 * Primary content in *BookingFeatures → Default → Primary*
 */
export interface BookingFeaturesSliceDefaultPrimary {
  /**
   * feature 1 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_1: prismic.RichTextField;

  /**
   * feature 2 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_2: prismic.RichTextField;

  /**
   * feature 3 field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.feature_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  feature_3: prismic.RichTextField;

  /**
   * additional information field in *BookingFeatures → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_features.default.primary.additional_information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  additional_information: prismic.RichTextField;
}

/**
 * Default variation for BookingFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingFeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingFeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BookingFeatures*
 */
type BookingFeaturesSliceVariation = BookingFeaturesSliceDefault;

/**
 * BookingFeatures Shared Slice
 *
 * - **API ID**: `booking_features`
 * - **Description**: BookingFeatures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingFeaturesSlice = prismic.SharedSlice<
  "booking_features",
  BookingFeaturesSliceVariation
>;

/**
 * Item in *DayByDayAccordionContent → Default → Primary → additional information*
 */
export interface DayByDayAccordionContentSliceDefaultPrimaryAdditionalInformationItem {
  /**
   * icon field in *DayByDayAccordionContent → Default → Primary → additional information*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.additional_information[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * description field in *DayByDayAccordionContent → Default → Primary → additional information*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.additional_information[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *DayByDayAccordionContent → Default → Primary → experience card*
 */
export interface DayByDayAccordionContentSliceDefaultPrimaryExperienceCardItem {
  /**
   * exp image field in *DayByDayAccordionContent → Default → Primary → experience card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[].exp_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  exp_image: prismic.ImageField<never>;

  /**
   * remark field in *DayByDayAccordionContent → Default → Primary → experience card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: remarks for image
   * - **Default Value**: iconic
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[].remark
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  remark: prismic.SelectField<
    "iconic" | "optional" | "trafalgar" | "travel-matter",
    "filled"
  >;

  /**
   * title field in *DayByDayAccordionContent → Default → Primary → experience card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *DayByDayAccordionContent → Default → Primary → experience card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * status field in *DayByDayAccordionContent → Default → Primary → experience card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: included
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[].status
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"included" | "paid", "filled">;
}

/**
 * Primary content in *DayByDayAccordionContent → Default → Primary*
 */
export interface DayByDayAccordionContentSliceDefaultPrimary {
  /**
   * day number field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.day_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  day_number: prismic.KeyTextField;

  /**
   * title field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * additional information field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.additional_information[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  additional_information: prismic.GroupField<
    Simplify<DayByDayAccordionContentSliceDefaultPrimaryAdditionalInformationItem>
  >;

  /**
   * included and optional exp field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.included_and_optional_exp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  included_and_optional_exp: prismic.KeyTextField;

  /**
   * experience card field in *DayByDayAccordionContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_accordion_content.default.primary.experience_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience_card: prismic.GroupField<
    Simplify<DayByDayAccordionContentSliceDefaultPrimaryExperienceCardItem>
  >;
}

/**
 * Default variation for DayByDayAccordionContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDayAccordionContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DayByDayAccordionContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DayByDayAccordionContent*
 */
type DayByDayAccordionContentSliceVariation =
  DayByDayAccordionContentSliceDefault;

/**
 * DayByDayAccordionContent Shared Slice
 *
 * - **API ID**: `day_by_day_accordion_content`
 * - **Description**: DayByDayAccordionContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDayAccordionContentSlice = prismic.SharedSlice<
  "day_by_day_accordion_content",
  DayByDayAccordionContentSliceVariation
>;

/**
 * Item in *DayByDayItinerary → Default → Primary → locations*
 */
export interface DayByDayItinerarySliceDefaultPrimaryLocationsItem {
  /**
   * image field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * day number field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].day_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  day_number: prismic.RichTextField;

  /**
   * day remarks field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].day_remarks
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  day_remarks: prismic.SelectField<"trafalgar" | "travel-matter">;

  /**
   * title field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * event 1 field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].event_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  event_1: prismic.ImageField<never>;

  /**
   * event 1 title field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].event_1_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  event_1_title: prismic.KeyTextField;

  /**
   * event 2 field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].event_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  event_2: prismic.ImageField<never>;

  /**
   * event 2 title field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].event_2_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  event_2_title: prismic.KeyTextField;

  /**
   * accordion content field in *DayByDayItinerary → Default → Primary → locations*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[].accordion_content
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  accordion_content: prismic.ContentRelationshipField<"day_by_day_accordion">;
}

/**
 * Primary content in *DayByDayItinerary → Default → Primary*
 */
export interface DayByDayItinerarySliceDefaultPrimary {
  /**
   * title field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * download field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.download
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  download: prismic.KeyTextField;

  /**
   * print field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.print
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  print: prismic.KeyTextField;

  /**
   * expand field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.expand
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  expand: prismic.KeyTextField;

  /**
   * collapse field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.collapse
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collapse: prismic.KeyTextField;

  /**
   * locations field in *DayByDayItinerary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: day_by_day_itinerary.default.primary.locations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  locations: prismic.GroupField<
    Simplify<DayByDayItinerarySliceDefaultPrimaryLocationsItem>
  >;
}

/**
 * Default variation for DayByDayItinerary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDayItinerarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DayByDayItinerarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DayByDayItinerary*
 */
type DayByDayItinerarySliceVariation = DayByDayItinerarySliceDefault;

/**
 * DayByDayItinerary Shared Slice
 *
 * - **API ID**: `day_by_day_itinerary`
 * - **Description**: DayByDayItinerary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DayByDayItinerarySlice = prismic.SharedSlice<
  "day_by_day_itinerary",
  DayByDayItinerarySliceVariation
>;

/**
 * Item in *Faq → Default → Primary → qna*
 */
export interface FaqSliceDefaultPrimaryQnaItem {
  /**
   * question field in *Faq → Default → Primary → qna*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.qna[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faq → Default → Primary → qna*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.qna[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * expand field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.expand
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  expand: prismic.KeyTextField;

  /**
   * collapse field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.collapse
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collapse: prismic.KeyTextField;

  /**
   * qna field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.qna[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  qna: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQnaItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *TopTourSummary → Default → Primary → year*
 */
export interface TopTourSummarySliceDefaultPrimaryYearItem {
  /**
   * year field in *TopTourSummary → Default → Primary → year*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.year[].year
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;
}

/**
 * Primary content in *TopTourSummary → Default → Primary*
 */
export interface TopTourSummarySliceDefaultPrimary {
  /**
   * Top Tour Image field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.top_tour_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  top_tour_image: prismic.ImageField<never>;

  /**
   * trip year field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  trip_year: prismic.RichTextField;

  /**
   * year field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.year[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  year: prismic.GroupField<Simplify<TopTourSummarySliceDefaultPrimaryYearItem>>;

  /**
   * title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * travel field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.travel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  travel: prismic.RichTextField;

  /**
   * travel content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.travel_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  travel_content: prismic.RichTextField;

  /**
   * accomodation field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.accomodation
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accomodation: prismic.RichTextField;

  /**
   * accomodation content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.accomodation_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  accomodation_content: prismic.RichTextField;

  /**
   * meals field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.meals
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meals: prismic.RichTextField;

  /**
   * meals content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.meals_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  meals_content: prismic.RichTextField;

  /**
   * itinerary field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.itinerary
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itinerary: prismic.RichTextField;

  /**
   * itinerary content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.itinerary_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  itinerary_content: prismic.RichTextField;

  /**
   * cta title field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_title: prismic.RichTextField;

  /**
   * cta content field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.cta_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cta_content: prismic.RichTextField;

  /**
   * trip code field in *TopTourSummary → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: top_tour_summary.default.primary.trip_code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  trip_code: prismic.RichTextField;
}

/**
 * Default variation for TopTourSummary Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TopTourSummarySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TopTourSummary*
 */
type TopTourSummarySliceVariation = TopTourSummarySliceDefault;

/**
 * TopTourSummary Shared Slice
 *
 * - **API ID**: `top_tour_summary`
 * - **Description**: TopTourSummary
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TopTourSummarySlice = prismic.SharedSlice<
  "top_tour_summary",
  TopTourSummarySliceVariation
>;

/**
 * Item in *TripMap → Default → Primary → legend*
 */
export interface TripMapSliceDefaultPrimaryLegendItem {
  /**
   * icon field in *TripMap → Default → Primary → legend*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * label field in *TripMap → Default → Primary → legend*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *TripMap → Default → Primary*
 */
export interface TripMapSliceDefaultPrimary {
  /**
   * title field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * map field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.map
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  map: prismic.ImageField<never>;

  /**
   * legend field in *TripMap → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: trip_map.default.primary.legend[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legend: prismic.GroupField<Simplify<TripMapSliceDefaultPrimaryLegendItem>>;
}

/**
 * Default variation for TripMap Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripMapSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TripMapSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TripMap*
 */
type TripMapSliceVariation = TripMapSliceDefault;

/**
 * TripMap Shared Slice
 *
 * - **API ID**: `trip_map`
 * - **Description**: TripMap
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TripMapSlice = prismic.SharedSlice<
  "trip_map",
  TripMapSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DayByDayAccordionDocument,
      DayByDayAccordionDocumentData,
      DayByDayAccordionDocumentDataSlicesSlice,
      ItineraryDocument,
      ItineraryDocumentData,
      ItineraryDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutTripSlice,
      AboutTripSliceDefaultPrimaryDetailsItem,
      AboutTripSliceDefaultPrimary,
      AboutTripSliceVariation,
      AboutTripSliceDefault,
      BookingFeaturesSlice,
      BookingFeaturesSliceDefaultPrimary,
      BookingFeaturesSliceVariation,
      BookingFeaturesSliceDefault,
      DayByDayAccordionContentSlice,
      DayByDayAccordionContentSliceDefaultPrimaryAdditionalInformationItem,
      DayByDayAccordionContentSliceDefaultPrimaryExperienceCardItem,
      DayByDayAccordionContentSliceDefaultPrimary,
      DayByDayAccordionContentSliceVariation,
      DayByDayAccordionContentSliceDefault,
      DayByDayItinerarySlice,
      DayByDayItinerarySliceDefaultPrimaryLocationsItem,
      DayByDayItinerarySliceDefaultPrimary,
      DayByDayItinerarySliceVariation,
      DayByDayItinerarySliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryQnaItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      TopTourSummarySlice,
      TopTourSummarySliceDefaultPrimaryYearItem,
      TopTourSummarySliceDefaultPrimary,
      TopTourSummarySliceVariation,
      TopTourSummarySliceDefault,
      TripMapSlice,
      TripMapSliceDefaultPrimaryLegendItem,
      TripMapSliceDefaultPrimary,
      TripMapSliceVariation,
      TripMapSliceDefault,
    };
  }
}
